"""empty message

Revision ID: 51fed7e9596d
Revises: 3b50db5d99a7
Create Date: 2020-03-09 19:21:57.408010

"""

# revision identifiers, used by Alembic.
revision = '51fed7e9596d'
down_revision = '3b50db5d99a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
