"""empty message

Revision ID: 8e7911870c38
Revises: 978733c02fed
Create Date: 2020-03-09 14:58:21.581539

"""

# revision identifiers, used by Alembic.
revision = '8e7911870c38'
down_revision = '978733c02fed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('member', sa.Column('gym_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'gym_id')
    op.drop_table('gym_owner')
    ### end Alembic commands ###
