"""empty message

Revision ID: b1c5527023a1
Revises: None
Create Date: 2020-03-08 18:27:35.148700

"""

# revision identifiers, used by Alembic.
revision = 'b1c5527023a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
