"""empty message

Revision ID: 37277a7a0cc9
Revises: 51fed7e9596d
Create Date: 2020-03-09 20:36:02.305809

"""

# revision identifiers, used by Alembic.
revision = '37277a7a0cc9'
down_revision = '51fed7e9596d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
